apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: forebygge-sykefravaer
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  ingresses:
    - https://arbeidsgiver.dev.nav.no/forebygge-sykefravaer
  liveness:
    path: /forebygge-sykefravaer/internal/isReady
    initialDelay: 10
  readiness:
    path: /forebygge-sykefravaer/internal/isReady
    initialDelay: 10
  accessPolicy:
    outbound:
      external:
        - host: i.vimeocdn.com
        - host: api.vimeo.com
        - host: cdn.sanity.io
        - host: dekoratoren.dev.nav.no
  envFrom:
    - secret: forebygge-sykefravaer-secrets
