apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: forebygge-sykefravaer
  namespace: default
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  ingresses:
    - https://arbeidsgiver-q.nav.no/forebygge-sykefravaer
    - https://arbeidsgiver.dev.nav.no/forebygge-sykefravaer
  liveness:
    path: /forebygge-sykefravaer/internal/isReady
    initialDelay: 10
  readiness:
    path: /forebygge-sykefravaer/internal/isReady
    initialDelay: 10
  vault:
    enabled: true
  webproxy: true
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: "/etc/ssl/ca-bundle.pem"
    - name: DECORATOR_EXTERNAL_URL
      value: https://dekoratoren.dev.nav.no/?context=arbeidsgiver
