apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: forebygge-sykefravaer
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  ingresses:
    - https://arbeidsgiver.dev.nav.no/gcp-forebygge-sykefravaer
  liveness:
    path: /forebygge-sykefravaer/internal/isReady
    initialDelay: 10
  readiness:
    path: /forebygge-sykefravaer/internal/isReady
    initialDelay: 10
  vault:
    enabled: true
  webproxy: true
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: "/etc/ssl/ca-bundle.pem"
  accessPolicy:
    outbound:
      external:
        - host: https://i.vimeocdn.com
        - host: https://api.vimeo.com
        - host: https://cdn.sanity.io
